---
- name: Remove templates
  ansible.builtin.file:
    path: "{{ dokuwiki_install_dir }}/lib/tpl/{{ item }}"
    state: absent
  with_items: "{{ dokuwiki_templates }}"

- name: Download and install templates (using git)
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ dokuwiki_install_dir }}/lib/tpl/{{ item.name }}"
    version: "{{ item.version }}"
  with_items: "{{ dokuwiki_templates }}"

- name: Set ownership and permissions for plugins
  ansible.builtin.file:
    path: "{{ dokuwiki_install_dir }}/lib/tpl/{{ item.name }}"
    owner: "{{ dokuwiki_user }}"
    group: "{{ dokuwiki_group }}"
    mode: 0755
  with_items: "{{ dokuwiki_templates }}"
