---
- name: Remove unnecessary plugins
  ansible.builtin.file:
    path: "{{ dokuwiki_install_dir }}/lib/plugins/{{ item }}"
    state: absent
  with_items: "{{ dokuwiki_remove_plugins }}"
  when: dokuwiki_remove_plugins is defined

- name: Download and install plugins
  block:
    - name: Download plugins
      ansible.builtin.get_url:
        url: "{{ item.src }}"
        dest: "{{ dokuwiki_install_dir }}/lib/plugins/{{ item.name }}.tar.gz"
      with_items: "{{ dokuwiki_plugins }}"

    - name: Create plugins directory
      ansible.builtin.file:
        path: "{{ dokuwiki_install_dir }}/lib/plugins/{{ item.name }}"
        state: directory
        owner: "{{ dokuwiki_user }}"
        group: "{{ dokuwiki_group }}"
        mode: 0755
      with_items: "{{ dokuwiki_plugins }}"

    - name: Extract plugins
      ansible.builtin.unarchive:
        src: "{{ dokuwiki_install_dir }}/lib/plugins/{{ item.name }}.tar.gz"
        dest: "{{ dokuwiki_install_dir }}/lib/plugins/{{ item.name }}"
        owner: "{{ dokuwiki_user }}"
        group: "{{ dokuwiki_group }}"
        remote_src: yes
        extra_opts: ["--strip-components=1"]
        mode: 0755
      with_items: "{{ dokuwiki_plugins }}"

  when: dokuwiki_plugins is defined

