---
- name: Remove unnecessary plugins
  ansible.builtin.file:
    path: "{{ dokuwiki_install_dir }}/lib/plugins/{{ item }}"
    state: absent
  with_items: "{{ dokuwiki_remove_plugins }}"

- name: Download and install plugins (using git)
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ dokuwiki_install_dir }}/lib/plugins/{{ item.name }}"
    version: "{{ item.version }}"
  with_items: "{{ dokuwiki_plugins }}"

- name: Set ownership and permissions for plugins
  ansible.builtin.file:
    path: "{{ dokuwiki_install_dir }}/lib/plugins/{{ item.name }}"
    owner: "{{ dokuwiki_user }}"
    group: "{{ dokuwiki_group }}"
    mode: 0755
  with_items: "{{ dokuwiki_plugins }}"
